export const GET_PROCESSES = 'GET_PROCESSES';
export const PROCESS_ERROR = 'PROCESS_ERROR';
export const DELETE_PROCESS = 'DELETE_PROCESS';
export const ADD_PROCESS = 'ADD_PROCESS';
export const ADD_SUBPROCESS = 'ADD_SUBPROCESS';
export const REMOVE_SUBPROCESS = 'REMOVE_SUBPROCESS';